require("bawj.plugins")
require("bawj.tex")
require("bawj.lsp")
require("bawj.cmp")
require("bawj.treesitter")
require("bawj.telescope")
require("bawj.trouble")
require("bawj.comment")
require("bawj.lualine")
require("bawj.nvim-tree")
require("bawj.gitsigns")
require("bawj.bufferline")
-- require("bawj.harpoon")
-- require("bawj.dap")
-- require("bawj.go_nvim")
require("fidget").setup({})
